name: Wolf Studio
favicon: null
layout_spectrum: 0
typography_spectrum: 0.39682
title: Wolf Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08159093093127012
  lightness: 0.75
  saturation: 0.22197540034539998
  rhythmicContrast: 0.1246244206558913
purpose: []
